global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds

scrape_configs:
  - job_name: 'get-express-api-metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
